name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Environment
        run: |
          pip install -r requirements.txt

      - name: Run Test
        working-directory: ./test
        run: |
          pip install pytest-report pytest-cov
          pytest --durations=0 --junitxml=pytest.xml | tee pytest-coverage.txt
      - name: Pytest Coverage Comment
        id: coverageComment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          hide-comment: true
          pytest-coverage-path: ./test/pytest.xml
      - name: Write Job Summary
        id: check_status
        run: |
          echo -e ${{ steps.coverageComment.outputs.summaryReport }} >> $GITHUB_STEP_SUMMARY
