name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Environment
        run: |
          pip install -r requirements.txt

      - name: Run test
        env:
          pytest_github_report: true
        working-directory: ./test
        run: |
          pip install pytest-github-report pytest-cov
          pytest --cov=. --cov-report=html
