name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          # fetch-depth: 0

      - name: Check tagged branch
        run: |
          BRANCHES=$(git branch --contains ${{ github.ref_name }})
          set -- $BRANCHES
          for BRANCH in $BRANCHES; do
            if [[ "$BRANCH" == "main" ]]; then
              exit 0
            fi
          done
          exit 1

      - name: Build module
        run: |
          pip install build
          python -m build

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
